cockpit-project/cockpit-files

- package.json
- src/app.jsx
- src/app.scss
- test/check-application
> Add details sidebar 

- src/app.scss
Use a blue color for folders (standard color on GNOME, KDE, & macOS; sometimes used on Windows too).
Also provide hover and selected state colors.
Colors are specified for both light and dark modes.
> Style icons with color

- src/app.jsx
- src/app.scss
- src/fileActions.jsx
- src/header.jsx
- src/sidebar.jsx
I've split apart my WIP and refactored it quite a bit to fix a bunch of layout-related issues.
Fixes #55
While this does use grid for layout, it doesn't use a grid for everything. I tried, but the layout is too complex as-is, so I went with the sticky solution that I proposed in the issue instead (so the information is still available).
I did remove the PF truncation component as it does not support line clamping. But, with wrapping and line clamping to 3 lines, truncation is not needed nearly as much. (Truncation still happens with an ellipsis when needed, but only at the end. This is a limitation on the way CSS supports truncation. But, as it's rarely needed now with the line wrapping, it's probably a fine tradeoff.)
I've tried to mimic what GNOME's file manager (Nautilus) does for …
> Improve layout in several ways

- src/app.jsx
Fixes 2 issues:
1. If multiple items are selected, Enter would navigate into last selected item if it's a folder
2. De-selecting an item and hitting Enter caused an error
> Only register Enter key when one item is selected

- src/sidebar.jsx
- test/check-application
We don't have to parse file output, file has `--brief` which only outputs the description.
> Simplify obtaining the file type

- src/app.jsx
- test/check-application
fixes: #147
Treat symbolic links to directories like a normal directory and make the folder icon blue.
> Make symlinks to directories icon blue

- test/check-application
SyntaxWarning: invalid escape sequence '\ '
> test: fix invalid escape sequence warning

- test/check-application
We don't run `make codecheck` yet as the JS code does not pass yet with:
```
```
So this only fixes the Python parts.
> Python lint fixes

- Makefile
- src/apis/spawnHelpers.jsx
- src/common.js
- src/fileActions.jsx
- test/check-application
- drop rename support
- drop recursive chmod support
before:
after:
> Two changes for the properties dialog

- .github/codeql-config.yml
- .github/workflows/codeql.yml
Scan our JavaScript code in src/ with codeql, we explicitly only include our own code as otherwise codeql will complain about build.js.
> .github: add codeql workflow for JavaScript

- src/app.jsx
- src/sidebar.jsx
- test/check-application
We have a few cases of something like:
```js
cockpit.format(_("Copy $0"), selected.type);
```
which would be bad enough if `selected.type` were a localized string. In this case, though, `type` is an English language internal attribute which was never intended to show to the user.
Let's stop doing this and just "Copy", "Rename" and "Delete".  The item that we're performing the operation on is clear from context.
> Undo some string pasting with English text

- src/app.jsx
- src/sidebar.jsx
- test/check-application
We have a dialog for editing permissions, with "permissions" in the title, but we consistently call the menu item "Edit properties".
Change the menu item to match the dialog title.
Closes #207
> Context menus: Use "Edit permissions" consistently

- Makefile
- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/common.ts
- src/fileActions.jsx
- src/fsinfo.ts
- src/sidebar.jsx
- test/browser/browser.sh
- test/browser/main.fmf
- test/check-application
- test/install-wheel
Substantially rework navigator to be based on the new 'fsinfo' channel provided by Cockpit.
This new channel is only on the Python bridge, and has yet to appear in a released version of Cockpit, so (unconditionally) re-engage our existing code to install a version of the wheel from cockpit git.
We also temporarily host some code here (fsinfo.ts) which will eventually make its way into cockpit.js.
In addition to being a simplification of the code, this *dramatically* improves the performance of cockpit-navigator, making it possible to open large directories, such as /usr/lib64.  Some quick measurements on that directory show that it takes only 58ms until we get the full set of data from the channel and convert it into the list of files for the navigator.  From there, the performance of …
> Use cockpit's new 'fsinfo' channel

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/context-menu.jsx
- src/fileActions.jsx
- src/navigator-card-body.jsx
- src/sidebar.jsx
- test/check-application
This PR aims to move the ContextMenu into the NavigatorCardBody as it has no place in `app.jsx` plus remove the context menu related event listeners to the NavigatorCardBody and stop having a per Item event listener for the Context Menu.
This is now so far all preparation work, I have a patch to make it use on `onContextMenu` but that requires more work to handle the folder switching breaks contextMenu bug.
> Refactor Navigator Card Body for global event listeners

- src/manifest.json
As discussed in the recent SPUR, rename navigator to "File browser" which is more obvious then navigator. Further more add some keywords so users can find it, as the old 45Drives project was called navigator allow it to be found when searching for navigator.
> Show navigator as file browser in Cockpit

- src/fileActions.jsx
- test/check-application
Resolves: https://github.com/cockpit-project/cockpit-navigator/issues/170 https://github.com/cockpit-project/cockpit-navigator/issues/169
Same approach is needed for the rename dialog as follow up.
> Create directory validation

- src/app.jsx
- src/fileActions.jsx
- src/navigator-card-body.jsx
- src/navigatorBreadcrumbs.jsx
- src/sidebar.jsx
- test/check-application
Prepare for the contextmenu and the dropdown menu to be merged together into one component. For this to happen drop everything not required from the sidebar menu.
After that we need to fix the insanity which is the current selected state. Right clicking sets the current path into state while the sidebar just assumes it acts on the current dir. Once that is refactored we can combine the actions into one and drop a ton of duplicate code.
New UI:
> Prepare for re-usable contextmenu/dropdown items

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/fileActions.jsx
- src/navigatorBreadcrumbs.jsx
- src/sidebar.jsx
This drops currentDir where possible except in the navigatorCardBody, it can be dropped there after we merge https://github.com/cockpit-project/cockpit-navigator/pull/254
An alternative approach is maybe to add `src/utils.ts` and then add a helper called `getCurrentDir(path: []string) => string` for looking up the directory name.
> Drop currentDir where possible

- .github/workflows/release.yml.disabled
The unit-tests container was dropped in
https://github.com/cockpit-project/cockpit/commit/f16f1fc14b88c
Also switch the template to current actions/checkout version.
Cherry-picked from https://github.com/cockpit-project/starter-kit/commit/6e1427493a
> workflows: Switch release to cockpit/tasks container

- .github/workflows/release.yml.disabled
This gets rid of the obsolete node.js 16. See
https://github.com/cockpit-project/action-release/commit/7d2e2657382e8
---
This isn't actually active yet, but let's bump it now so that we don't forget.
> workflows: Bump action-release to get github-script@v7

- src/app.tsx
- src/fileActions.jsx
- src/navigator-card-body.jsx
- src/sidebar.jsx
- test/check-application
Merge the two menu's into one helper function, this reduces a ton of code duplication, simplifies and unifies everything. As side-effect removes renaming the current directory.
> Unify menus cleanups

- pyproject.toml
- test/check-application
These aren't unused, but discovered/enumerated by `unittest` or `pytest`.
> lint: Ignore test functions in vulture

- src/navigator-card-body.jsx
- test/check-application
When a directory is empty inform the user and reserve enough space for the contextmenu to still function.
Closes: #113
---
> Show that the directory is empty

- src/app.tsx
- src/header.jsx
- src/navigator-folder-view.tsx
- src/settings-dropdown.jsx
- test/check-application
Cockpit cleans up all localStorage settings which are not prefixed with the application, the application name comes from the url itself where it is named "navigator", not "cockpit-navigator".
> Remember localStorage settings after logout

- src/navigator-card-body.jsx
The contextmenu component's event listeners are installed on the DOM element with the id being `navigator_parent_id`. This should always be the parent of the contextMenu otherwise click events aren't handled by the ContextMenu component as the contextMenu is not a child in the DOM.
Moving the ContextMenu in the div with the cards causes the layout to change on a right click, which is unwanted.
> Ensure contextmenu is the child of it's parentId

- test/browser/browser.sh
So that things like TEST_AUDIT_NO_SELINUX can be set from the outside.
> tmt: Pass TEST_* environment into test container

- src/fileActions.jsx
- test/check-application
Support downloading a single selected file using the fsread1 channel, additionally don't offer this button when the logged in user lacks the permission to read the file.
---
This superseeds https://github.com/cockpit-project/cockpit-files/pull/175
> Add download support for files

- src/fileActions.jsx
- src/files-card-body.jsx
- test/check-application
This PR should add coverage for [keydown eventlistener](https://cockpit-logs.us-east-1.linodeobjects.com/pull-357-5d6166f7-20240404-205754-fedora-39-devel/Coverage/src/files-card-body.jsx.gcov.html) and implement the missing delete button functionality with a test.
> Implement delete button event handling and introduce keyboard navigation tests

- src/apis/spawnHelpers.jsx
- src/fileActions.jsx
When deleting fails we get presented with another modal the force delete modal. This modal is identical except the text and the displayed error. Merge those two while this does not make a lot of sense as they end up calling `rm` again with the same arguments this will need to be handled in a follow up.
> Merge Confirmation and Force deletion modal

- .github/dependabot.yml
The type annotations get new releases very often and cause too much CI churn/conflicts otherwise.
react and react-dom need to be kept in sync.
> dependabot: Group React and typescript related packages

- src/fileActions.jsx
The superuser option is documented in our protocol docs as an optional string. The bridge converted true to `require` but in this instance /etc/login.defs is world readable so should not require superuser.
> /etc/login.defs is word-readable

- .flake8
- pyproject.toml
Ruff's preview rules now implements the rules which we used flake8 for.
> test: enable ruff preview rules

- src/files-card-body.jsx
This compares the `selected` object against a string, Typescript already warns this makes no sense when I converted this a to a `tsx` file.
> Drop useless conditional

- packit.yaml
Provide COPR main builds for folks who are interested in testing files and later to eventually reverse test Cockpit-files in Cockpit.
Closes: #394
---
Same as https://github.com/cockpit-project/cockpit-podman/pull/1365
> packit.yaml: provide copr main builds for testing

- src/fileActions.jsx
In 337c1e6cbdcf0c590 we introduced file download support which always adds a divider regardless if the file can be downloaded.
Closes: #392
> Don't always add a divider in context menu's

- src/fileActions.jsx
In db968b2700cf26780522e8 we unified the sidepanel menu and the contextmenu so they would be identical. This removed the ability to rename the current directory, this is not something GNOME Files supports or something we want to support.
> Drop rename current directory code

- src/fileActions.jsx
- test/check-application
This feature has plenty of issues and needs to be reworked to be a lot more simple. Either it will just create a link like GNOME Files as absolute link or relative link which would require more thought when moving.
> Drop create link / paste as symlink functionality

- src/fileActions.jsx
- test/check-application
A user cannot chown of regular files, so this UI option would always fail, until we have proper polkit support hide this option.
> Hide ownership permission editing for non-admin access

- src/app.tsx
prevAlerts.filter() returns a new Array so we don't have to spread it to create a new array.
Found by oxlint's eslint-unicorn-plugin rule.
> Don't spread an already newly created Array

- src/fileActions.jsx
By using `getent` we can obtain users and groups from for example FreeIPA as well and as this is displayed in a dialog we do not require watching /etc/passwd or /etc/group.
---
As discussed, a follow up from last week https://github.com/cockpit-project/cockpit-files/pull/430#discussion_r1590195988
> Use getent to obtain users and groups

- src/fileActions.jsx
- test/check-application
We rename in Files by moving the file to the new filename but when this is a directory `mv` moves the file to that directory instead. This is quite logical in a shell but not in a GUI, there it is unexpected behaviour.
Related: #399
---
Note this is a partial fix, we want to actually pass files to the dialog to check if a directory or file already exists. However in no circumstance do we want a rename to move a file under an existing directory. So we should always invoke `mv` with `--no-target-directory`.
> Renaming to existing directory name moves under directory

- src/app.scss
- src/files-breadcrumbs.tsx
- test/check-application
Allow the user to specify the full path with a TextInput, this allows quick navigator from `/home/admin` to for example `/opt`.
Closes: #116
---
I looked at the PenPot design and there are two variants. I have implemented one but we can switch to the other one if desired.
Some example screenshots:
New view:
When editing:
Some known issues:
* no blur handing, as the button is separate from the Input, adding blur to the input makes it always cancel. I assume losing focus should "cancel editing". Alternative, addBlur with a `setTimeout` of 2/3/5 seconds which cancels editing.
* We need to decide on a final design, which shouldn't be a lot more work to change.
* Lack of integration tests
Some notes:
Patternfly has an [inline editing example](https://www.patternfly.org/components/inline-edit) …
> Allow editing of path

- .github/workflows/weblate-sync-pot.yml
As far as I know this requires a token to deploy which we need to get deployed by https://github.com/cockpit-project/bots/pull/6380
Verified that a pot file is created locally.
```
[jelle@t14s][~/projects/cockpit-navigator]%make  po/files.pot
pkg/lib/html2po.js -o po/files.html.pot $(find src -name '*.html')
xgettext --default-domain=files --output=po/files.js.pot --language=C --keyword= \
--add-comments=Translators: \
--keyword=_:1,1t --keyword=_:1c,2,2t --keyword=C_:1c,2 \
--keyword=N_ --keyword=NC_:1c,2 \
--keyword=gettext:1,1t --keyword=gettext:1c,2,2t \
--keyword=ngettext:1,2,3t --keyword=ngettext:1c,2,3,4t \
--keyword=gettextCatalog.getString:1,3c --keyword=gettextCatalog.getPlural:2,3,4c \
--from-code=UTF-8 $(find src/ -name '*.js' -o -name '*.jsx')
pkg/lib/manifest2po.js …
```
> .github: add weblate sync pot file workflow

- test/check-application
These where accidentally removed when removing the symlink functionality.
> test: re-add copy/paste tests

- src/files-breadcrumbs.tsx
A path can have the same directory so make sure the keys are actually unique.
> Make sure the breadcrumb has unique keys

- src/app.tsx
- src/files-folder-view.tsx
- src/header.tsx
- src/index.d.ts
- src/upload-button.scss
- src/upload-button.tsx
- test/check-application
This implements https://github.com/cockpit-project/cockpit-files/issues/378 
----
Conflict handling
> Implement upload support

- packaging/arch/PKGBUILD.in
Quoting is needed when using versioned depends.
==> WARNING: Skipping all source file integrity checks.
/startdir/PKGBUILD: line 8: syntax error near unexpected token `>'
/startdir/PKGBUILD: line 8: `depends=(cockpit>=310.1)'
> packaging: quote the depends with a version comparison

- src/files-breadcrumbs.tsx
- test/check-application
When editing the path and we are at the root directory the path in the input should resemble `/`. The path is stored as an array so join('/') gives "" instead of `/`. Later we want the path to on longer be an array but the real full path.
> Editing the path of the root dir should show / in the input

- src/common.ts
- src/fileActions.jsx
- src/files-card-body.jsx
- src/sidebar.jsx
- test/check-application
When copy pasting pass the `--archive` flag to `cp` so permissions are retained. This also allows us to enable superuser try as permissions are now retained.
Related: #435
> Remove paste into folder functionality, Check for the existence of a file or directory when pasting

- src/sidebar.jsx
This is a simple fix, as there isn't enough room for the sidebar to have labels on the side. This moves the labels in the list to the top and therefore doesn't make the sidebar always grow when something is selected (vs. not).
The mockups had labels on the top; I think having it on the side was an oversight and copied from much of the rest of Cockpit with labels on the side... there just isn't enough room for it here.
> sidebar: Headers should be above in a limited space

- Makefile
- packaging/arch/PKGBUILD.in
- packaging/cockpit-files.spec.in
- packaging/debian/control
The fsreplace1 send-acks feature was added in 316.
> packaging: bump Cockpit requirement for send-acks

- Makefile
...and make `make check` go via `make vm` so that it benefits as well.
This shaves quite some seconds off of image building (42s instead of 1m36s).  Most of that comes from compressing node_modules/ which seems like the obvious candidate to get rid of, but it's required by the build.  We could work around that, but it would involve some deeper hacks, so let's make the easy change, instead.
> Makefile: use `XZ_OPT=-0` for `make vm`

- src/app.scss
- src/files-card-body.jsx
- src/files-card-body.scss
- src/files-folder-view.tsx
- src/header.tsx
- test/check-application
`
`.pf-v5-c-sidebar__main, .pf-v5-c-sidebar__content, .pf-v5-c-card { height: 100%; }`
> Useful listing table

- .github/workflows/dependabot.yml
- .github/workflows/reposchutz.yml
- .gitignore
- .gitmodules
- Makefile
- packaging/cockpit-files.spec.in
- packit.yaml
Build and maintain the node_modules/ as a submodule, using the tools/node-modules script as it's done in the cockpit repo.
Updating the node_modules/ directory after changing package.json now involves running `tools/node-modules install` and then committing the result, and pushing the submodule commit with `tools/node-modules push`.
Copy the dependabot workflow to make sure things get properly rebuilt when our `node_modules` label is set (as dependabot does for us).
> Makefile: switch to node_modules/ as submodule

- src/dialogs/mkdir.tsx
- src/fileActions.jsx
- src/ownership.tsx
- test/check-application
If we have superuser capabilities, then add a drop-down list to the "Create directory" dialog with possible ownerships for the create directory.
By default we try to create the new directory with the same owner as the parent, but also have options for root:root or the user:group of the logged in user (if it is different from the parent directory).
The logic for determining the potential owners of newly created items is generic and might also be applied to things like upload, so keep it in its own file.
Also, move the dialog into a new file: src/dialogs/mkdirt.tsx. fileActions has become a bit too much of a catch-all.
Todo:
> Add ownership options for "Create directory"

- src/files-card-body.jsx
- test/check-application
Fixes a bug introduced in e1664765bc8de371dbb9dad64c71625e701bead0.
The file category is only present on regular files, but we access it unconditionally on anything that isn't a directory.  That causes crashes when entering /dev or anywhere else that contains devices, sockets, or FIFOs.
Make the access conditional and add a test for entering /dev.
Fixes #507
> Don't crash on special files

- Makefile
- packaging/cockpit-files.spec.in
- packit.yaml
This is a partial revert of e64ce8d7b10e1a0fd5d2625e07bd592edb8ab59c.
It's Fedora policy that we run esbuild during the rpm phase, so let's bring back the tarball with the things required to do that and include it in the packaging again.
We need to add a bit of a hack here: when we create the tarball we set all timestamps to the same value.  If `dist/` is missing, then we make sure `package-lock.json` is up to date before trying to run esbuild, but since all timestamps are the same, `make` will conclude that it needs to be rebuilt.  In turn, that calls `tools/node-modules`, which gets upset because it's not in a git checkout.  We can short-circuit that by touching `package-lock.json` when we delete `dist/`.
> Makefile: bring back the -node.tar.xz artifact

- src/files-card-body.jsx
- src/files-card-body.scss
- test/check-application
This bug was introduced by 45aa7686f82d5b8f7ea2e which makes the content area stretch except the contextmenu div which this PR fixes and adds a test that right clicking in the middle of the div works.
> Resize the contextmenu area to the full height of the folder view

- src/files-card-body.scss
This PR differentiates between hovers and selections, plus it reworks focusing (via mouse and also keyboard) too.
Hovering is still grey, but selection is a light blue, similar to both Nautilus and some parts of PatternFly, such as toggle groups https://www.patternfly.org/components/toggle-group
> Rework hover, selection, and focus styling

- Makefile
This is definitely not needed, and it's big.
> Makefile: don't add node_modules/.git/ to the release

- src/files-card-body.jsx
- test/check-application
The result is smaller code that's easier to understand.  This also fixes sorting of directories before files when sorting by size.
Fixes #530
> Simplify and fix sorting options

- pyproject.toml
- src/files-card-body.jsx
- test/check-application
This avoids showing a meaningless '0 B' (or misleading arbitrary other size) for folders.  Other special files also lack a meaningful size, so don't show them either.
Symlinks are a bit of a tricky case here: we currently show the size of the link (which is the length of the link target in bytes).  We could show the size of the target, but this is a bit odd.  Let's show nothing.
Fixes #531
> Only show size for regular files

- src/app.tsx
- src/event.ts
- src/filetype-lookup.ts
- src/fsinfo.ts
Also, eject our self-rolled callback mechnism and change to the standard EventTarget API.
In order to keep type safety of the event types that we use, write a small wrapper, TypedEventTarget.  This is "mostly" safe, but we need a couple of casts: from the types on the standard EventTarget API, all event listener functions must support being called with all types of events, but ours only support being called with their specific event types.
This is starting to get ready for inclusion in the main cockpit library.
> fsinfo: change to class-based style

- packit.yaml
Now that we have an official release and are in Fedora, it's time to enable this.
Fixes #561
> packit: Enable COPR/Fedora releases

- Makefile
Partially revert commit 2fe12b8f. Debian testing now has Cockpit 318, and our bots image is up to date again.
> Go back to using Debian testing cockpit-ws package

- test/check-application
The test was flaky as changing the directory didn't wait for the state to fully sync so a paste would paste in the previous directory.
Additionally add a check that after pasting going back to the original folder still shows the copied file.
Enable the upload test for debian-testing as we have Cockpit > 311 now.
> Various test fixes / maintainence

- test/check-application
We landed the PR to introduce pixel tests — #570 — in parallel with a PR that changed the visual style of the app — #574.
Update the pixel tests to adjust for the changes from #574.
Fixes #575
> test/reference: update to unbreak main

- src/fileActions.jsx
- src/files-card-body.jsx
- src/files-card-body.tsx
- src/files-folder-view.tsx
- src/header.tsx
- src/menu.tsx
- src/settings-dropdown.tsx
- src/sidebar.jsx
- test/check-application
If we tie on the mtime or the file size then fall back to sorting based on name — it's always unique.
This should give us a fully-defined sort order for all directories.
> Fall back to sorting by name on ties

- src/app.tsx
This fixes two issues, the "No such file or directory" view now shows the EmptyStatePanel properly centered and with the expected background colour. (The same background colour as the normal folder view.
Closes: #568
---
Expected pixel test failures: https://cockpit-logs.us-east-1.linodeobjects.com/pull-587-d56fe411-20240621-150917-fedora-40/log.html
Broken view:
New view:
> Wrap EmptyStatePanel in a Card for consistency

- Makefile
- src/dialogs/delete.tsx
- src/dialogs/mkdir.tsx
- src/dialogs/permissions.jsx
- src/dialogs/rename.tsx
- src/download.tsx
- src/files-card-body.tsx
- src/index.d.ts
- src/index.tsx
- src/menu.tsx
- src/sidebar.jsx
- src/sidebar.tsx
- src/upload-button.tsx
- test/check-application
- finish up the job of killing off `src/fileActions.jsx`, splitting it into many separate files
- clean up the interface used to show dialogs — each dialog now has a function to call instead of the caller having to construct and Dialogs.show() the widget themselves
- adapt to the new `Dialogs.run()` interface, dropping all uses of `Dialogs.show()` and `Dialogs.close()`
- the usual obligatory typescript porting
Of course, this first:
> lots of code restructuring

- src/app.scss
- src/files-breadcrumbs.tsx
- test/check-application
Closes: #522
---
Users can now bookmark the current directory and easily navigate to previously bookmarked directories.
> Implement bookmark support

- packit.yaml
Fedora 41 is around the corner and as this is a relatively new package it does not make sense to push it to cockpit-files to Fedora 39.
> packit.yaml: don't release to Fedora-39

- org.cockpit-project.files.metainfo.xml
As otherwise there is nothing filled in applications page:
> Add summary to metainfo

- package.json
This is already in devDependencies. It has no place in the runtime dependencies.
> package.json: Clean up duplicate eslint-config-standard-react

- src/download.tsx
- test/check-application
So as described in #602, it isnt able to properly encode non-latin1 characters and `btoa` fails to encode it.
`TextEncoder` nets you the underlying utf8 bytes, which `btoa` is also not able to handle directly. But I did take @allisonkarlitskaya suggestion and didnt rely on `cockpit.base64_encode`, instead just apply every byte as its own character to btoa.
I have added a test, but I have tried to use the tasks container to run it, but I keep getting failures that I cant figure out. I think it is environmental issue, and has nothing to do with the test harness itself.
> Properly handle non-latin1 filename in downloads

- package.json
Since commit 34191c5ffcbcd45 nothing uses this dependency any more.
> package.json: Drop date-fns

- src/files-folder-view.tsx
- test/check-application
When a user clicks on a different path or double clicks a folder reset the search filter.
> Reset search filter on navigation

- packit.yaml
- test/browser/browser.sh
- test/browser/run-test.sh
This should help catch gating issues and now we can test the first commit of this PR which passes TEST_OS down to the host.
> build & test centos stream 9 / 10

- packaging/cockpit-files.spec.in
Cockpit-files will never work on RHEL 8 as it needs a newer Cockpit (318 or higher).
> packaging: drop rhel8 specific BuildRequires

- src/dialogs/rename.tsx
- test/check-application
fixes: #468
Renaming file to a filename which already exists now causes the original file to be replaced with the renamed file.
For now this is only allowed for normal files and links to normal files since directories would require recursive merging.
> Allow overriding when renaming

- test/check-application
It sometimes (RHEL 9 gating test) happens that the browser/mobile layout are set up so that three columns fit in one row. In this case, moving the cursor down lands at `file3`. Accept that as well.
---
This fixes one half of the RHEL 9 gating test failure. The [other half](https://artifacts.dev.testing-farm.io/2dbc2ef2-6c5e-430a-bbec-1039a5b6cc42/) (`testBookmark`) happens sometimes in upstream PRs as well, and looks like a race condition in either the code or the test.
> test: Allow three column layout in testKeyboardNav

- test/browser/browser.sh
If the env has a main-builds COPR (for reverse dependency tests), we always want to install the latest version from that. So give it the highest priority (uninutitively, lower priority wins), and use `distro-sync` to up- or downgrade the package as necessary, and consider *only* the COPR.
Also show the cockpit-{files,bridge} package versions in the log, to make this kind of failure cause more obvious.
Similar to https://github.com/cockpit-project/cockpit/commit/7ab102a551
----
This hopefully helps with the [random revdeps failures](https://artifacts.dev.testing-farm.io/7ad20935-9828-4cbc-81f7-40ee8c5b3ade/) which we are seeing. The log does not currently show the package version, but the failures smell like the main tests are running against an old cockpit-files rpm version.
> fmf: Fix installation of our main-builds COPR

- test/check-application
On the latest Fedora 40 image [1], /home/admin contains an extra `.bash_history` hidden file which breaks the "empty-folder-view" pixel test: there are now 5 instead of 4 hidden directories.
Do this pixel test in a self-created directory to make it more predictable.
[1] https://github.com/cockpit-project/bots/pull/6605
---
Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6605-f678fe28-20240711-051123-fedora-40-cockpit-project-cockpit-files/log.html).
> test: Do empty directory pixel test in controlled directory

- src/app.scss
- test/check-application
In the testing farm gating environment the hostname is quite long which changed the overall layout to have 3 items in the top row and one in the bottom row. This causes the keyboard nav to fail and in general layout issues, the problem is that we breadcrumbs should not be buttons but anchors this will be worked on in a follow up.
> Allow paths in the breadcrumb to wrap

- src/manifest.json
The default content-security-policy of cockpit-bridge is enough for files it already includes `img-src: 'self' data:` and `frame-src` is not needed as we don't have or want any iframes or frames in files.
---
https://github.com/cockpit-project/cockpit/blob/main/src/cockpit/packages.py#L291
> manifest: drop content-security-policy

- src/app.scss
- src/files-breadcrumbs.tsx
Explain the bookmark and edit path button with a tooltip.
Related: #581
> Add tooltips for bookmark and edit path buttons

- src/app.tsx
- src/files-card-body.tsx
- src/files-folder-view.tsx
- test/check-application
Make the emptyState actionable when no items are found when filtering by allowing the user to clear the search filter. When a folder is empty but hidden items are found, allow a user to show the hidden items.
---
> Improve empty state for filtering/empty folders

- test/check-application
We tested that the selector changed, but never tested setting the selector as a user, see coverage: https://cockpit-logs.us-east-1.linodeobjects.com/pull-661-2bb5c2bb-20240718-155256-fedora-40-devel/Coverage/src/dialogs/permissions.jsx.gcov.html
> test: test the permissions dialog group selector

- src/common.ts
- src/files-card-body.scss
- src/files-card-body.tsx
- src/header.tsx
- test/check-application
fixes: #565
Adds permissions column to details view with the ability to sort by permissions. Sorting is done by comparing permission octal values.
---
Users can now view file permissions directly within the interface for a greater control over the file management. It is also possible to sort files by their permissions from most permissive or least permissive.
> Add file permissions to details view

- src/app.scss
- src/files-breadcrumbs.tsx
- test/check-application
PatternFly has a breadcrumb component which we where not using but instead used a button which meant we could not properly support middle click and needed to apply css workarounds to style them properly.
Middle mouse click now properly works and opens the clicked path in a new tab.
Closes: #641
> Implement the breadcrumb with PatternFly components

- src/app.tsx
- src/common.ts
- src/dialogs/permissions.jsx
- src/dialogs/rename.tsx
- src/files-breadcrumbs.tsx
- src/files-card-body.tsx
- src/files-folder-view.tsx
- src/header.tsx
- src/menu.tsx
- src/sidebar.tsx
- src/upload-button.tsx
- test/check-application
There is no good reason to keep the path as an array of strings, usually we want to just append a file to the path for file operations as most of the code simply joined the path back to a string.
This also makes sure the path is properly formatted as /path/to/thing/ with a leading and trailing /.
---
> Keep the path as string instead of an array

- test/check-application
This was missing in the test coverage.
> test: test for a user specifying a path without a /

- test/check-application
The `#sidebar-card-header` also contains the file type, which appears a moment after clicking on the file name. Make the selector more specific to not include the file type component.
---
Fixes [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-700-f64d734e-20240811-193008-debian-testing/log.html#17-1), which became very apparent in #700.
> test: Fix race in TestFiles.testUpload

- packit.yaml
Also replace "latest-stable" with a more direct "40". We do that in all other projects, and there's less ambiguity during times when a release was forked, but isn't declared "stable" yet.
> packit: Add Fedora 41

- src/app.scss
The new SASS version warns that decelerations should appear above nested rules. This change should not have any visual impact.
> ▲ [WARNING] Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}`.
> css: move CSS declarations above nested rules

- test/check-application
This [fixes rhel-9-5 runs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-6760-6cb82890-20240819-124109-rhel-9-5-cockpit-project-cockpit-files/log.html) (see https://github.com/cockpit-project/bots/pull/6760) and also tightens a check.
I triggered an extra [rhel-9-5 run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-713-0bae87a9-20240819-132012-rhel-9-5/log.html) here (it's currently in _manual).
> test: Fix timeout for waitDownloadFile()

- src/files-card-body.scss
- src/files-card-body.tsx
- src/header.tsx
- test/check-application
Fixes: #580
Sorting is currently as follows:
- directories first
- by user
- by group
- filename
I'd like to think about if we should sort current user first (as #580 mentions), I'm not sure if I like the idea but I want to check it out.
> Add owner column to details view

- pyproject.toml
- test/check-application
We have a lot of cases of this pattern in the tests:
```sh
runuser -u admin echo something > /some/file
```
which successfully runs the 'echo' command as the admin user, but performs the redirection (and therefore file creation) as root, which is clearly not the desired result.
Change those over to use m.write() with the `owner=` kwarg.
> test: fix attempts to write files as admin

- .eslintrc.json
- build.js
- src/app.tsx
- src/dialogs/mkdir.tsx
- src/dialogs/permissions.jsx
- src/dialogs/rename.tsx
- src/download.tsx
- src/files-breadcrumbs.tsx
- src/files-card-body.tsx
- src/files-folder-view.tsx
- src/filetype-data.d.ts
- src/filetype-plugin.ts
- src/header.tsx
- src/index.tsx
- src/menu.tsx
- src/ownership.tsx
- src/sidebar.tsx
- src/upload-button.tsx
- tsconfig.json
It's currently not possible to run ./build.js under node-22, which is a shame, because we'll want to be able to do that soon (due to upcoming TypeScript support, which will let us stop using tsx and its bundled copy of esbuild, simplifying builds on arm64).
Reading the developments on the addition of TypeScript support to Node, it seems to be the case that TypeScript is somewhat isolated in their opinion on the correct approach for handling extensions on import statements.  Indeed, node-22 will outright break if we don't use extensions correctly.
Add back the extensions that we removed from the files in our build process.  Change our use of the eslint rule to *require* extensions, rather than forbid them, and update our code accordingly.  Updating our bundled code is not strictly …
> all: change approach to extensions on imports

- src/dialogs/editor.scss
- src/dialogs/editor.tsx
- src/menu.tsx
- test/check-application
---
Users can now edit and view small text files.
Viewing:
Editing:
File changed on disk while editing:
> Implement viewer/editor for text files

- src/common.ts
- src/dialogs/permissions.jsx
- src/files-breadcrumbs.tsx
- src/menu.tsx
- src/sidebar.tsx
Drop our own implementation in favour of the shared cockpit-lib one.
> Re-use basename from cockpit's new path lib

- src/app.scss
- src/app.tsx
- src/dialogs/keyboardShortcutsHelp.tsx
- src/files-breadcrumbs.tsx
- src/files-card-body.tsx
- src/header.tsx
- src/menu.tsx
- test/check-application
fixes: #451
For now this adds following keybindings:
- `alt + arrow up`: go up one directory
- `alt + arrow down`: activate selected item, enter directory
- `Enter`: activate selected item, enter directory
- `ctrl + shift + L`: focus files breadcrumbs to manually edit it
- `F2`: rename selected file
- `shift + N`: create new directory
- `ctrl + c`: copy file/directory
- `ctrl + v`: paste file/directory
- `ctrl + a`: select all files
Alt + arrow left/right is already supported by cockpit files browser
history.
---
> Add basic keyboard shortcuts

- src/dialogs/delete.tsx
- src/dialogs/editor.tsx
- src/dialogs/permissions.jsx
- test/check-application
Unify them to all use the form `$action <b>$name</b>` so all dialog titles use the same style.
---
> dialogs: unify the dialog titles

- src/download.tsx
This fixes trying to download a remotely connected host, without setting the host header the fsread1 request will go to the "shell host" and not the currently viewed machine.
Closes: #773
> Support downloading with the multi-host feature

- Makefile
- org.cockpit_project.files.metainfo.xml
Rename the file to match its ID, fix the ID, add developer tag, and extend the description. This fixes all issues with `appstreamcli validate`:
> org.cockpit-project.files.metainfo.xml
>  I: org.cockpit_project.cockpit_files:22: description-first-para-too-short
>       A file system browser for Cockpit.
>  I: org.cockpit_project.cockpit_files: developer-info-missing
>  W: org.cockpit_project.cockpit_files: metainfo-filename-cid-mismatch
> appstream: Fix validation problems

- package.json
Copied from starter-kit.
Hopefully avoids issues like https://github.com/cockpit-project/cockpit-files/issues/791
Fixes #791
> package.json: require nodejs 16 or higher

- .github/workflows/dependabot.yml
Our dependabot workflow is unable to deal with conflicting node_modules when we land one of the dependabot pull requests. The manual workflow before was to let dependabot re-create the pull request and then add the `node_modules` label after re-recreating the pull request. Automating this is tricky as a Github workflow cannot automate the recreate comment as it has no write permissions to our projects.
The new approach when adding a `node_modules` label will always rebase the pull request and in case of a conflict will remove the conflicting node_modules changes in the commit. Afterwards we create the new node_modules commit which can be merged.
---
Partially tested here https://github.com/jelly/cockpit-navigator/pull/11 re-adding the `node_modules` label now rebases and the new commit …
> workflows: teach dependabot workflow to rebase

- .github/dependabot.yml
- package.json
sass 1.80 (and 2.x) introduces tons of "@import rules are deprecated". These are unfixable on our side due to PatternFly using them extensively.
We don't need any new sass features, so stick to 1.79.x. Explicitly not ignore 3.x (which will drop @import) to get a reminder in the future to try and clean this up again.
Same as https://github.com/cockpit-project/cockpit/pull/21155
Fixes #799
> package.json: Revert to sass 1.79

- .github/dependabot.yml
Major PF updates always need to be done in Cockpit first, due to all the overrides and lib.
> dependabot: Keep PatternFly at current major version

- .github/dependabot.yml
Commit c5a22e1eb4 was ineffective due to `update-types` not having a correct value. See
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore
---
Fixes #807
> dependabot: Fix PatternFly update-types

- src/dialogs/permissions.jsx
- test/check-application
The preparation work in 3599a486cb470799a5eb1e3 opens the way to support implementing `chmod -R`, by splitting the execute permissions from the dropdown options. The split was needed as when recursively changing permissions files would unnecessarily get an executable bit this does not happen when we pass `-X`. The `-X` option only adds the executable bit where required.
---
The permissions dialog now supports changing the permissions of all enclosed files and directories.
> Support changing permissions of enclosed files or directories

- src/dialogs/rename.tsx
- test/check-application
This is what PatternFly advices and is consistent with the rest of our validation error messages.
---
Was brought up in the "create object PR" which needs a rebase anyway.
> test: remove punctuation from validation error messages

- src/dialogs/mkdir.tsx
- test/check-application
This is what PatternFly advices and is consistent with the rest of our validation error messages.
> Remove punctuation from validation errors in create directory dialog

- test/check-application
This part of the test flaked in that it didn't change directory to /etc/. A likely cause is that drop_superuser() does not wait on the page to fully load so the `b.go()` never registered in cockpit-files.
> test: wait on files to load after dropping superuser

- src/common.ts
- src/dialogs/create-file.tsx
- src/dialogs/editor.scss
- src/dialogs/editor.tsx
- src/dialogs/rename.tsx
- src/menu.tsx
- test/check-application
---
Files can now create a new file with initial content after creation the dialog changes into editor mode so you can keep editing. When you have "administrative access" the owner of the file is pre-selected based on the owner of the directory so far /home/admin/ it is "admin:admin" and you can also change ownership to root if needed.
> Create file support

- test/reference-image
Adjust the mobile icon list pixel ref for the disabled host switcher on Fedora 41.
> test: Move reference-image to Fedora 41

- .github/dependabot.yml
We don't want sass 1.82 etc. either. Judging by the release history there won't be any 1.79.x any more, and we don't need them either.
Closes #867
> dependabot: Ignore all sass 1.x versions

- src/dialogs/permissions.css
- src/dialogs/permissions.tsx
- src/menu.tsx
- test/check-application
Blocked:
As discussed on Thursday, for multiple file uploads we want to allow users to change multiple file(s) permissions to be changed. This has been implemented with the following restrictions:
* Only multiple files can be edited, not block devices, fifo's, directories etc.
* Don't show SELinux context as it makes no sense for multiple files
* Don't allow changing of the owner/group if they don't match between files (so not to have inconsistency)
---
The permissions of multiple selected files can now be changed.
> Allow editing multiple file permissions

- src/app.tsx
- src/upload-button.scss
- src/upload-button.tsx
- test/check-application
Files could not yet support uploading to non-logged in user directories as these files would always be uploaded as `root:root` and this might not be wanted in directories not owned by `root`.
---
Cockpit-files now allows you to upload files into directories not owned by the logged in user, when you are administrator. It will by default upload the file with the same user/group as the current directory. You can change the ownership after uploading.
> Support uploading files with administrator privileges

- src/app.scss
- src/files-card-body.scss
- src/files-card-body.tsx
- src/files-folder-view.tsx
- src/upload-button.tsx
- test/check-application
@tomasmatus interested?
One tricky thing here is we already have an upload-button component, so the eventlistener should be set up there instead so we don't have to pass `files` around.
---
It is now possible to upload files by simply dragging them from your desktop or a file explorer and dropping them directly into Cockpit Files.
> Drag 'n drop

- src/files-footer-detail.tsx
- test/check-application
Hello,
Here with my two cents. This is my first commit.
Adding user:group to the file footer
> Added user:group to the file footer.

- test/check-application
When opening an empty dir, we expect the "Directory is empty" empty state to *appear*. Checking for its absence is a race condition. Additionally verify that the breadcrumb shows the expected directory.
Drop the redundant wait_visible() before the click.
---
I ran into this in #917 all the time, and it's also very prominent on the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-files&days=7):
> test: Fix empty dir check in testPermissions

- test/check-application
Similar to commit b045f17402, this test changes into an empty (except for 3 hidden files) directory. So wait for that. This fixes a race condition where the test would only succeed if the empty state wasn't rendered too fast.
---
[failure 1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-917-9928627b-20250128-090420-fedora-41/log.html#19-2), [failure 2](https://cockpit-logs.us-east-1.linodeobjects.com/pull-917-9928627b-20250128-080848-fedora-41/log.html#19-1)
Spotted in #917 due to 3x affected tests.
> test: Fix empty dir check in testUpload

- Makefile
- test/check-application
- test/vm-ws.install
cockpit-files currently works fine on RHEL 8 with beibooting. Let's keep
it that way: Add a rhel-8.10/ws-container scenario that runs the tests
through our ws container.
Fixes #914
---
> test: Add ws-container scenario

- src/app.tsx
- src/common.ts
- src/dialogs/create-file.tsx
- src/dialogs/delete.tsx
- src/dialogs/keyboardShortcutsHelp.tsx
- src/dialogs/mkdir.tsx
- src/dialogs/permissions.tsx
- src/dialogs/rename.tsx
- src/download.tsx
- src/files-breadcrumbs.tsx
- src/files-card-body.tsx
- src/files-folder-view.tsx
- src/files-footer-detail.tsx
- src/header.tsx
- src/menu.tsx
- src/upload-button.tsx
Fix imports to avoid importing from `app.tsx` and use `import type` where possible.
Add missing license to keyboardShortcutsHelp.tsx
> Fix imports and add missing license

- packaging/cockpit-files.spec.in
Now that https://fedoraproject.org/wiki/Changes/Replace_Cockpit_Navigator_With_Cockpit_Files is approved, let's get this into Fedora.
> Replace cockpit-navigator with cockpit-files

- packit.yaml
Similar to https://github.com/cockpit-project/cockpit-podman/pull/1993
> packit: Drop copr_build job redundancy, re-disable Fedora 42

- src/app.scss
This was fixed in October last year in PatternFly 5.
---
Pixel tests should prove this.
> app.scss: drop PF override which is no longer applicable

- src/dialogs/permissions.tsx
- test/check-application
Symlinks have no permissions you can change so we shouldn't show this option. The owner/group can be changed and that is a valid use case however they shouldn't operate on the target.
> Handle symlink permissions correctly

- src/dialogs/create-file.tsx
- src/dialogs/editor.css
- src/dialogs/editor.tsx
- src/files-card-body.css
- src/files-card-body.tsx
- src/upload-button.css
- src/upload-button.tsx
PatternFly 6 fully removed CSS from their code base and since CSS these days is modern enough to support everything we need from SASS.
> Convert SCSS where possible to CSS

- src/dialogs/delete.tsx
Change default focus to the Delete button instead of "x" on the top-right side of the modal. This allows workflow to delete files by hitting delete + enter key.
> focus delete button in delete modal

- test/check-application
Fix some b.go() issues where we don't really assert anything changes and thus we don't wait on `fsinfo` to load a new state and instead act on the old state.
> test: get a handle on those flakes!

- test/check-application
Since 3.9 we can use `list[str]` or `| None` and since our testing container has a way more modern version this is safe to change.
> test: use modern typing hints

- test/check-application
This works fine now.
---
... at least locally; the comment doesn't say whether it e.g. only doesn't work in TF or so, let's see.
> test: Enable testUpload on Firefox

- test/check-application
The test changes into an empty directory so waiting for the empty state not to be present is a race.
> test: fix flake in testErrors

- src/app.tsx
- src/common.ts
- src/dialogs/keyboardShortcutsHelp.tsx
- src/files-card-body.tsx
- test/check-application
fixes: #757
---
Files now supports MacBook flavored keyboard shortcuts to natively fit into the Apple ecosystem.
> Support Mac specific keybinds

- src/app.tsx
- src/common.ts
- test/check-application
* usePath is silly and should just be `get_path` on the current location
* introduce helper `wait_on_directory`
* generalize switching directories with a helper (ie. replace b.go() with `def chdir(path): b.go(path); self.wait_chdir(path` )
*  cleanups cleanups!
> Solve the directory switching flakes once and for all

- packaging/cockpit-files.spec.in
Our Fedora/RHEL packaging does not do any building in the `%build` step.
> packaging: drop nodejs build requirement

- src/app.tsx
- src/index.tsx
After 5958cae075457af1a2914 we now initially load a folder twice, once `/` as the user is not loaded yet and once we loaded the user we load `/home/admin`. This leads to an annoying visual flash when logging in.
> Start loading the directory when the user is available

- src/dialogs/symlink.tsx
- src/menu.tsx
- test/check-application
Allow the creation of absolute or relative symlinks from the target. The symlink input field can be a filename, an absolute or relative path and are either symlinked as relative or absolute depending on the selected option.
The symlink permissions are not configurable and by default based on the owner of the directory so creating a symlink as administrator in the users home directory creates it as `admin:admin`.
---
Files can now create relative or absolute symlinks for files or directories in the current directory.
> Create symlink support

- src/app.tsx
- src/common.ts
- src/dialogs/copyPasteOwnership.tsx
- src/dialogs/create-file.tsx
- src/dialogs/mkdir.tsx
- src/files-breadcrumbs.tsx
- src/upload-button.tsx
Now that `Application` is guaranteed to have a valid `user` it can also be provided via the FilesContext. This removes the needs for a `useInit` or `useEffect` to obtain the `user` object in dialogs or other components.
---
This is sparked by your comment in the symlink PR @martinpitt instead of passing it down everywhere I just added it to the widely available context. In reality it can never be `null` but due to how `createContext works` it has to be optionally null.
> Provide `user` in the FilesContext

- src/app.tsx
- src/common.ts
- src/dialogs/copyPasteOwnership.tsx
- src/dialogs/create-file.tsx
- src/dialogs/mkdir.tsx
- src/files-breadcrumbs.tsx
- src/index.tsx
- src/ownership.tsx
- src/upload-button.tsx
Instead of using `cockpit.user()`, switch to getting the same information from `cockpit.info`.  We have to call `cockpit.init()` to have that initialized, but once it's done, we no longer have to route the data around through the entire codebase.
This PR is a sort of proof of concept for the work in https://github.com/cockpit-project/cockpit/pull/21733
*Manual testing*: You can test this locally by manually updating the cockpit commit in the Makefile to whatever the latest in https://github.com/cockpit-project/cockpit/pull/21733 is, then building an image of that branch *from inside cockpit project* using `test/image-prepare`, then running that image with `vm-run -s cockpit.socket`, then (back in cockpit-files) running `./build.js -rc` inside of this branch in cockpit-files, then logging …
> src: stop plumbing 'user' around

- src/download.tsx
The Python bridge does have a maximum read size limit while the C bridge did. We want to add a maximum read size back to 16MB but that would break files users and we can't introduce an "unlimited" option (-1) as that would be incompatible with older Python bridge versions. So temporarily we set the max size to something very big `MAX_SAFE_INTEGER` which is 2^53. When we bump the cockpit-bridge requirement in files we can set it to "unlimited".
> Temporary set max_read_size of Cockpit to MAX_SAFE_INTEGER

- test/check-application
Re-open the context menu after each layout change in the pixel test.
This slightly changes the pixel tests due to the rounded corners.
----
[pixel diff](https://github.com/cockpit-project/pixel-test-reference/compare/e13f780f59b86b5615073b5938048872990d1a68..10952d73639cf24f9d960a8a0dbcf9d472792615)
Also fixes the [testDownload flake](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-files&days=14&test=%2Ftest%2Fcheck-application+TestFiles.testDownload) and the [testBasic](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-files&days=14&test=%2Ftest%2Fcheck-application+TestFiles.testBasic) as well.
> test: Fix testContextMenu for real mouse clicks, fix test{Basic,Download} flakes

- build.js
When the build is cancelled in watch mode, `dist` might not exist so copying to it will always fail and show a long useless traceback. Unfortunately esbuild errors don't give much information so we can't match the exact cancelled error.
> build.js: don't copy assets when the build is cancelled

- src/dialogs/create-file.tsx
- test/check-application
We shouldn't permit empty files from being created, we should only
prevent when the filename is empty or there is validation errors.
Modifying an existing file already worked when emptying the content but
there were no tests for it. To reduce regressions an existing test was
expanded to cover modifying a file with content to an empty file.
Fixes: https://issues.redhat.com/browse/RHEL-79666
Signed-off-by: Freya Gustavsson <freya@venefilyn.se>
> dialogs: Allow user to create empty files
