- src/app.jsx
- Converted to functional component
- Removed unused code
- Split content into multiple components
> Convert Application to functional component

- src/app.jsx
[Screencast from 2023-05-10 23-22-22.webm](https://github.com/KKoukiou/cockpit-navigator/assets/90795679/477ad19b-cb87-4a1d-94f6-d8ea435887ef)
> Add double clicking and breadcrumbs

- src/app.jsx
> Add search field functionality

- src/app.jsx
- src/app.scss
- test/check-application
> Add "sort by" dropdown functionality

- src/index.js
This is already indirectly getting imported in pages.scss.
> Remove duplicate patternfly-5-overrides import

- src/app.jsx
Added `width_25` to make sidebar width fixed
> Fix inconsistent sidebar width

- .eslintrc.json
- src/app.jsx
- test/check-application
> Add delete button & kebab menu

- src/app.jsx
- test/check-application
> Add create directory button

- src/app.jsx
- src/context-menu.scss
- src/fileActions.jsx
- src/index.js
- src/navigator-context-menu.jsx
- test/check-application
> Add context menu

- src/app.jsx
> Add isInline prop to fix icon colors

- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
- test/check-application
> Add show hidden files button 

- src/app.jsx
> Set selected to file object instead of file name to correctly identify selected item

- src/app.jsx
- src/fileActions.jsx
- src/navigatorBreadcrumbs.jsx
- src/sidebar.jsx
- test/check-application
> Add functionality to ui navigation buttons

- src/app.jsx
- src/header.jsx
- test/check-application
> Sort directories before files

- src/app.jsx
> Truncate long file names

- package.json
- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
- test/check-application
> Add create link functionality

- Makefile
- package.json
- src/app.jsx
- src/app.scss
- src/fileActions.jsx
- src/header.jsx
- src/sidebar.jsx
- test/check-application
> Show/edit file/folder permissions

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/fileActions.jsx
- src/navigatorBreadcrumbs.jsx
- src/sidebar.jsx
split out of https://github.com/KKoukiou/cockpit-navigator/pull/77
> initial implementation of putting path in URL

- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
> Add link to item type

- src/app.jsx
- src/app.scss
- test/check-application
> Wrap buttons in selectable Card element

- src/app.jsx
- src/sidebar.jsx
- test/check-application
>  When the is an error with directory listing show empty state panel with the error message

- package.json
Filing in cockpituous' stead, it seems to have trouble with actually opening a PR. Permissions?
> package.json: Update throttle-debounce

- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
- test/check-application
Closes #101
Rearrange and adjust some buttons to follow the [mockups](https://photos.google.com/share/AF1QipNz1pguqHconQtLRH1HyIAYCHJxQ9ZyQaIS-BiJ99KeI4Z7Dp-54wIG90qcg0aS3g?pli=1&key=cEdxWDBQZGpaeTc1ZlRoMURKOXh1VVZlQjRuTlBB) better
> Improve menu/context menu

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
- test/check-application
> Multi-selection

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/fileActions.jsx
- src/sidebar.jsx
- test/check-application
> Add copy/paste buttons

- src/app.jsx
- src/navigatorContextMenu.jsx
> Show spinner when loading files

- src/fileActions.jsx
> Autofocus text input, enter key creates directory

- src/apis/spawnHelpers.jsx
- src/app.jsx
- src/fileActions.jsx
- src/navigatorBreadcrumbs.jsx
- src/sidebar.jsx
- test/check-application
> Fix eternal loading when selecting the root directory

- src/app.jsx
- src/sidebar.jsx
In my honest opinion we should up the line limit a bit from 120 loc
> Cleanup arrow functions with unneeded braces

- Makefile
- test/run
> Add coverage support

- .eslintrc.json
- .gitignore
- Makefile
- package.json
- src/cockpit.d.ts
- tsconfig.json
Broken out from #210, since that's likely to take a while.
> Experimental typescript support

- src/app.jsx
- src/sidebar.jsx
- test/check-application
> Store option for showing hidden files in localStorage

- src/fileActions.jsx
> Dialogs variant consistently

- .stylelintrc.json
- package.json
- src/app.scss
Follow up of https://github.com/cockpit-project/cockpit-navigator/pull/264
> Stylelint RTL support

- src/cockpit.d.ts
> cockpit.d.ts: annotate some location-related stuff

- src/app.tsx
- src/navigator-card-body.jsx
On first look, found two issues:
1. Creating a component inside the function body of another component creates a brand new component on every render, so React will update the *actual dom* thinking it's different every time, which shouldn't happen as [I mentioned here](https://github.com/cockpit-project/cockpit-navigator/issues/298#issuecomment-1976482702).
2. The `files` dependency of the `useMemo` was changing on every render making the memo useless.
> Perf Investigation

- src/header.jsx
- src/navigator-folder-view.tsx
- test/check-application
Since we've recently added `showHiddenItems` to localStorage, it also feels logical to include the view mode.
I've added a small test case but I'm not sure why it fails yet.
> Store isGrid option in localStorage

- .github/workflows/cockpit-lib-update.yml
- .gitignore
- README.md
- org.cockpit-project.files.metainfo.xml
- package.json
- packaging/arch/PKGBUILD.in
- packaging/cockpit-files.spec.in
- packaging/debian/changelog.in
- packaging/debian/control
- packaging/debian/copyright
- packaging/debian/source/lintian-overrides
- packaging/debian/upstream/metadata
- packit.yaml
- src/app.tsx
- src/files-breadcrumbs.tsx
- src/files-card-body.jsx
- src/files-folder-view.tsx
- src/header.jsx
- src/index.html
- src/manifest.json
- src/settings-dropdown.jsx
- test/check-application
This also requires to rename this repo. Please debate :)
> Rename to 'Files'

- .github/workflows/release.yml.disabled
- .github/workflows/tasks-container-update.yml
The quay.io location is obsolete, the image moved to GitHub registry.
> workflows: Run tasks-container-update.yml in quay.io/cockpit/tasks

- src/header.tsx
The other files (except files-card-body) need `cockpit.spawn` to be typed.
src/files-card-body.tsx needs me to learn DOM events and dealing with React.ref
> Port headers.jsx to tsx

- src/app.tsx
- src/fileActions.jsx
- src/files-card-body.jsx
- src/index.js
- src/sidebar.jsx
- test/check-application
Fixes the 4 issues in https://github.com/cockpit-project/cockpit-files/issues/395 except using `getent passwd` and `getent group` I'll look into that on Monday in https://github.com/cockpit-project/cockpit-files/issues/431
> Edit permissions crashes & improvements

- src/sidebar.jsx
- test/check-application
> Disable sidebar kebab when the directory is invalid

- src/app.scss
The class is no longer used since c0e0bfaa5a4096f7b2313.
> Drop unused css class

- src/files-card-body.scss
> Stretch the content area to fill the page

- src/app.scss
- src/files-card-body.jsx
- src/files-card-body.scss
- src/sidebar.jsx
This also paves the path for better mobile support too.
> Use grid for layout, fixing scroll and resize on select

- Makefile
- test/check-application
> test: Replace custom press_special_key() with standard testlib

- packaging/cockpit-files.spec.in
We submitted spec file as this, I sycned the suse change from podman.
> Update packaging from Fedora

- src/app.tsx
- src/dialogs/mkdir.tsx
- src/fileActions.jsx
- src/files-breadcrumbs.tsx
- src/files-card-body.jsx
- src/files-folder-view.tsx
- src/header.tsx
- src/settings-dropdown.jsx
- src/sidebar.jsx
- src/upload-button.tsx
This does not currently make any difference for the dist/ size because of https://github.com/patternfly/patternfly-react/issues/10618. But we do that in all other projects.
> Import selected PF components only

- src/app.scss
- src/files-breadcrumbs.tsx
> breadcrumb: Add style to the path divider

- README.md
- packaging/debian/control
- packaging/debian/copyright
Let's apply some polish and wax before [uploading this to Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076001)
> Debian packaging and README updates

- src/upload-button.tsx
- test/check-application
Add a pixel test to assert the text and layout of the upload conflict dialog.
> test: assert the contents of the upload conflict dialog

- src/dialogs/rename.tsx
- test/check-application
Fixes https://github.com/cockpit-project/cockpit-files/issues/622
> Rename directory modal issues

- src/files-breadcrumbs.tsx
- src/files-folder-view.tsx
- src/filetype-data.d.ts
- src/ownership.tsx
- src/upload-button.tsx
This makes no impact on the bundle size but generally is a good thing.
Closes: #596
> Use type import where applicable

- package.json
- src/files-folder-view.tsx
Not much to say, but it should be far less janky, i've used the same debounce amount from the files autocomplete in cockpit.
Fixes #669
> Debounce files filter

- src/app.scss
Pixel changes: https://cockpit-logs.us-east-1.linodeobjects.com/pull-684-5d343435-20240730-124122-fedora-40/log.html
> Menutoggle fixes

- src/dialogs/editor.tsx
src/dialogs/editor.tsx(181,11): error TS2578: Unused '@ts-expect-error' directive.
> remove unused `@ts-expect-error` directive

- src/app.scss
- src/app.tsx
- src/files-folder-view.tsx
- src/header.tsx
- src/sidebar.tsx
- test/check-application
relevant comment:
https://github.com/cockpit-project/cockpit-files/pull/567#issuecomment-2337581719
> Move global menu to the toolbar

- src/app.tsx
> remove empty dependency array in useInit

- test/browser/browser.sh
https://src.fedoraproject.org/rpms/shadow-utils/c/029086935e7eb96ea4e9f1e86984caaa113c593d?branch=rawhide
> test: drop shadow-utils workaround

- build.js
- src/dialogs/permissions.jsx
- src/dialogs/read-selinux.py
- test/check-application
> Selinux in permissions

- src/dialogs/editor.tsx
- test/check-application
Closes: #790
See changes here https://cockpit-logs.us-east-1.linodeobjects.com/pull-793-e31300d6-20241017-174719-fedora-40/log.html
> Show the filename in the title of the editor

- src/index.html
- src/menu.tsx
- test/check-application
From the context menu, add an option to open directories in the terminal.
Fixes #464
> Open directory in terminal

- src/files-breadcrumbs.tsx
- test/check-application
> Renamed add bookmark for better understanding

- packit.yaml
It started working yesterday evening.
> packit: Re-enable Fedora 42

- src/app.tsx
- src/dialogs/copyPasteOwnership.tsx
- src/dialogs/keyboardShortcutsHelp.tsx
- src/dialogs/rename.tsx
```
biome init
biome migrate eslint --write --include-inspired
```
> Fixes for issues found by biome

- src/index.html
This allows distributors and in the future admins [1] to customize Cockpit's pages via the branding mechanism.
See https://github.com/cockpit-project/cockpit/commit/a2bc632991e
[1] https://github.com/cockpit-project/cockpit/issues/21338
> Include branding.css
